version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - '6378:6378'

  langflow:
    image: langflowai/langflow:latest
    environment:
      - LANGFLOW_DEFAULT_FLOWS_PATH=/app/flows
      - REDIS_URL=redis://redis:6379
    ports:
      - '7860:7860'
    volumes:
      - ./flows:/app/flows
    depends_on:
      - redis
